### PR TITLE
Show all tests errors in CI

### LINKED ISSUE #977: Make insta not stop at the first failure
This allows us to identify all errors in a single run, instead of having to push fixes multiple times.

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes #977 in this way:
- Split integration tests in different tests 
- Regenerate all snapshots without prepending the module name to snapshot filename
- Do not stop CI at the first failure, showing all errors in one fell swoop

### CODE REVIEW

**Comment by marco-c** [comment]
@Luni-4 will it still return an error code in case of a failure?

**Comment by Luni-4** [comment]
Seems not

```console
running 3 tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/./repositories/rca-output/snapshots/serde/serde_test/test__build.rs.snap
Snapshot: build.rs
Source: tests/test.rs:52
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
   25    25 │                     total_closures: 0,
   26    26 │                 },
   27    27 │                 nexits: Stats {
   28    28 │                     exit: 1,
   29       │-                    exit_sum: 2,
         29 │+                    exit_sum: 1,
   30    30 │                     total_space_functions: 1,
   31    31 │                     exit_min: 1,
   32    32 │                     exit_max: 1,
   33    33 │                 },
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────
stored new snapshot /home/rust-code-analysis/tests/./repositories/rca-output/snapshots/serde/serde_test/test__build.rs.snap.new
To update snapshots run `cargo insta review`
test test_serde ... ok
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/./repositories/rca-output/snapshots/pdf.js/test__gulpfile.js.snap
Snapshot: gulpfile.js
Source: tests/test.rs:52
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
   21    21 │                     spaces: [],
   22    22 │                     metrics: CodeMetrics {
   23    23 │                         nargs: Stats {
   24    24 │                             fn_nargs: 0,
   25       │-                            closure_nargs: 4,
         25 │+                            closure_nargs: 3,
   26    26 │                             fn_nargs_sum: 0,
   27    27 │                             closure_nargs_sum: 3,
   28    28 │                             fn_nargs_min: 0,
   29    29 │                             closure_nargs_min: 3,
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────
stored new snapshot /home/rust-code-analysis/tests/./repositories/rca-output/snapshots/pdf.js/test__gulpfile.js.snap.new
To update snapshots run `cargo insta review`
test test_pdfjs ... ok
test test_deepspeech ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 14.92s
```

**Comment by marco-c** [comment]
That's not an acceptable solution then, we need to do something else

**Comment by Luni-4** [comment]
@marco-c 

This new approach works, tested locally

```console
running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/repositories/rca-output/snapshots/DeepSpeech/native_client/alphabet.cc.snap
Snapshot: alphabet.cc
Source: tests/common/mod.rs:58
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────
   59    59 │                     sloc: Sloc {
   60    60 │                         start: 7,
   61    61 │                         end: 38,
   62    62 │                         unit: fal,
   63       │-                        sloc_min: 34,
         63 │+                        sloc_min: 32,
   64    64 │                         sloc_max: 32,
   65    65 │                     },
   66    66 │                     ploc: Ploc {
   67    67 │                         lines: {
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────
stored new snapshot /home/rust-code-analysis/tests/repositories/rca-output/snapshots/DeepSpeech/native_client/alphabet.cc.snap.new
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'Consumer 2' panicked at 'snapshot assertion for 'alphabet.cc' failed in line 58', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Receiver("A thread used to process a file panicked")
error: test failed, to rerun pass `-p rust-code-analysis --test deepspeech_test`

Caused by:
  process didn't exit successfully: `/home/rust-code-analysis/target/debug/deps/deepspeech_test-5dda953ec9218cbb --nocapture` (exit status: 1)
     Running `/home/rust-code-analysis/target/debug/deps/pdf_js_test-d9e2409429c672af --nocapture`

running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/repositories/rca-output/snapshots/pdf.js/systemjs.config.js.snap
Snapshot: systemjs.config.js
Source: tests/common/mod.rs:58
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────
   29    29 │                             spaces: [],
   30    30 │                             metrics: CodeMetrics {
   31    31 │                                 nargs: Stats {
   32    32 │                                     fn_nargs: 2,
   33       │-                                    closure_nargs: 1,
         33 │+                                    closure_nargs: 0,
   34    34 │                                     fn_nargs_sum: 2,
   35    35 │                                     closure_nargs_sum: 0,
   36    36 │                                     fn_nargs_min: 2,
   37    37 │                                     closure_nargs_min: 0,
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────
stored new snapshot /home/rust-code-analysis/tests/repositories/rca-output/snapshots/pdf.js/systemjs.config.js.snap.new
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'Consumer 0' panicked at 'snapshot assertion for 'systemjs.config.js' failed in line 58', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Receiver("A thread used to process a file panicked")
error: test failed, to rerun pass `-p rust-code-analysis --test pdf_js_test`

Caused by:
  process didn't exit successfully: `/home/rust-code-analysis/target/debug/deps/pdf_js_test-d9e2409429c672af --nocapture` (exit status: 1)
     Running `/home/rust-code-analysis/target/debug/deps/serde_test-7143ca5d278065b8 --nocapture`

running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/repositories/rca-output/snapshots/serde/serde_derive_internals/build.rs.snap
Snapshot: build.rs
Source: tests/common/mod.rs:58
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────
   51    51 │                     cyclomatic_max: 2.000,
   52    52 │                     cyclomatic_min: 2.000,
   53    53 │                 },
   54    54 │                 halstead: Stats {
   55       │-                    u_operators: 13,
         55 │+                    u_operators: 9,
   56    56 │                     operators: 21,
   57    57 │                     u_operands: 9,
   58    58 │                     operands: 12,
   59    59 │                 },
────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────
stored new snapshot /home/rust-code-analysis/tests/repositories/rca-output/snapshots/serde/serde_derive_internals/build.rs.snap.new
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'Consumer 2' panicked at 'snapshot assertion for 'build.rs' failed in line 58', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Receiver("A thread used to process a file panicked")
error: test failed, to rerun pass `-p rust-code-analysis --test serde_test`

Caused by:
  process didn't exit successfully: `/home/rust-code-analysis/target/debug/deps/serde_test-7143ca5d278065b8 --nocapture` (exit status: 1)
     Running `/home/rust-code-analysis/target/debug/deps/rust_code_analysis_cli-1b24074797f61c4d --nocapture`

error: 3 targets failed:
    `-p rust-code-analysis --test deepspeech_test`
    `-p rust-code-analysis --test pdf_js_test`
    `-p rust-code-analysis --test serde_test`
```

**Review by marco-c — APPROVED** [review]

**Comment by marco-c** [comment]
There is a failure on CI with a now unused dependency

**Review by marco-c — APPROVED** [review]

**Comment by marco-c** [comment]
There are some compilation errors

**Comment by marco-c** [comment]
There are still problems on CI, this time with formatting

**Review by marco-c — APPROVED** [review]

**Pull request merged**
