### PR TITLE
Add a node variant

### PR DESCRIPTION
**Pull request by Luni-4**
This variant hides the crate used to handle nodes in the code.

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by calixteman** [comment]
Is this patch just aim to hide the `use tree_sitter::Node;` ?
Could you explain the exact rational ?

**Comment by Luni-4** [comment]
> Is this patch just aim to hide the `use tree_sitter::Node;` ?
> Could you explain the exact rational ?

Yep, the main goal is hiding `tree_sitter::Node` to users since in the documentation the `Node` struct is exported and I can't avoid showing it because that would mean a lack of documentation.

That's why I wanted to hide the library that handles nodes, at the same time the entire `tree_sitter` library is completely handled internally by `rust-code-analysis`

**Comment by Luni-4** [comment]
This one seems a bit complicated instead, I couldn't think an alternative solution

**Comment by calixteman** [comment]
Please rebase.

**Comment by Luni-4** [comment]
Done.

**Pull request merged**
