### PR TITLE
Fix cognitive metric when there are no functions

### PR DESCRIPTION
**Pull request by Luni-4**

### CODE REVIEW

**Comment by Luni-4** [comment]
@marco-c 

I propose to use the 0 approach instead of the `null` one when there are no functions. Since we are using a _counting_ approach, if something doesn't exist, the count remains set to 0

**Comment by marco-c** [comment]
I'm thinking we should use `null`, so users can differentiate an actual 0 cognitive complexity from a not-existent cognitive complexity.
Users who want to consider `null` as 0 can do so, and users who want to differentiate can do that too.
Instead, if we save 0 for everything, only the first kind of usage would be possible.

**Comment by Luni-4** [comment]
Seems good to me, I'm going to change the metrics in that way then

**Comment by Luni-4** [comment]
@marco-c 

Now it is ready

**Review by marco-c — APPROVED** [review]

**Pull request merged**
