### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by calixteman**
@marco-c could you check that everything is fine with bugbug since actix is updated here ?

### CODE REVIEW

**Comment by marco-c** [comment]
@calixteman this looks similar to 72317cebd8097f0782dd820532d87dc2ff994811, but I had to revert it because the web server was not working anymore (it was panicking at start). Is it not the case anymore?

**Comment by marco-c** [comment]
Yeah, I'm seeing:
```
thread 'main' panicked at 'System is not running', /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
```
when I run `cargo run -- --port 8080`.

**Comment by marco-c** [comment]
It's probably some version incompatibility, because in the Cargo.lock diff I see some packages now depending on `actix-rt 2.2.0` and some on `actix-rt 1.1.1`.

**Comment by calixteman** [comment]
Setting `actix-web = "4.0.0-beta.5"` fixes the problem.
We should wait for a new release, wdyt ?

**Comment by marco-c** [comment]
>  We should wait for a new release, wdyt ?

WFM

**Pull request closed without merging**
