### PR TITLE
Update grammars

### LINKED ISSUE #1083: I can't build rust-code-analysis by tree-sitter version conflicts with tree-sitter-rust
When I build the code, I can't build it with the following error: There is a version conflict between the dependencies, is there anything you are checking for this?

```
|
42  |           $name::language()
    |           ^^^^^^^^^^^^^^^^^ expected `tree_sitter::Language`, found a different `tree_sitter::Language`
...
264 |                   fn get_language() -> Language {
    |                                        -------- expected `tree_sitter::Language` because of return type
    |
   ::: /Users/jbpark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-code-analysis-0.0.25/src/langs.rs:8:1
    |
8   | / mk_langs!(
9   | |     // 1) Name for enum
10  | |     // 2) Language description
11  | |     // 3) Display name
...   |
116 | |     )
117 | | );
    | |_- in this macro invocation
    |
    = note: `tree_sitter::Language` and `tree_sitter::Language` have similar names, but are actually distinct types
note: `tree_sitter::Language` is defined in crate `tree_sitter`
   --> /Users/jbpark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-sitter-0.22.2/binding_rust/lib.rs:56:1
    |
56  | pub struct Language(*const ffi::TSLanguage);
    | ^^^^^^^^^^^^^^^^^^^
note: `tree_sitter::Language` is defined in crate `tree_sitter`
   --> /Users/jbpark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-sitter-0.20.9/binding_rust/lib.rs:43:1
    |
43  | pub struct Language(*const ffi::TSLanguage);
    | ^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `tree_sitter` are being used?
    = note: this error originates in the macro `get_language` which comes from the expansion of the macro `mk_langs` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rust-code-analysis` (lib) due to 1 previous error
```

### PR DESCRIPTION
**Pull request by alexle0nte**
This PR:
- Updates `tree-sitter` and grammars to the latest versions.
- Fixes #1083.

### CODE REVIEW

**Comment by aytey** [comment]
@alexle0nte: is there a chance you could undraft this? It seems your PR is the only way for me to build `rust-code-analysis`, so it would be great if these changes could be upstreamed.

**Comment by alexle0nte** [comment]
> @alexle0nte: is there a chance you could undraft this? It seems your PR is the only way for me to build `rust-code-analysis`, so it would be great if these changes could be upstreamed.

I will start working on this PR again in the coming days. I’ve noticed that, although the tests pass, there are errors in the computation of some metrics for certain languages due to the grammar version update.

**Comment by marco-c** [comment]
> > @alexle0nte: is there a chance you could undraft this? It seems your PR is the only way for me to build `rust-code-analysis`, so it would be great if these changes could be upstreamed.
> 
> I will start working on this PR again in the coming days. I’ve noticed that, although the tests pass, there are errors in the computation of some metrics for certain languages due to the grammar version update.

Ciao Alex. If there are more improvements than regressions, we could consider landing the changes anyway and filing follow-up issues for the regressions.

**Comment by alexle0nte** [comment]
Ciao @marco-c! Ok, so can we merge the PR even if not all tests pass, and then fix them in a new PR?

**Comment by marco-c** [comment]
Yes I think so, after all tests are failing on master anyway.

**Comment by marco-c** [comment]
@alexle0nte let me know when you're ready

**Comment by alexle0nte** [comment]
> @alexle0nte let me know when you're ready

It's ready for review

**Comment by marco-c** [comment]
I've filed #1091 for the follow-up work.

**Pull request merged**
