### PR TITLE
Move c_macros generation into the enums crate

### PR DESCRIPTION
**Pull request by Luni-4**
- Move  `c_macros` generation  to the `enums` crate in order to avoid recreating each `c_macro` file whenever the `rust-code-analysis` library is built.
- Replace `phf_set` with a const array

### CODE REVIEW

**Comment by marco-c** [comment]
Can we remove the `phf` dependency as part of this or is it still necessary?

**Comment by Luni-4** [comment]
> Can we remove the `phf` dependency as part of this or is it still necessary?

I would have done that in a following PR, but I can remove it in this PR

**Comment by marco-c** [comment]
> I would have done that in a following PR, but I can remove it in this PR

Yes, thanks, I'd prefer that

**Comment by marco-c** [comment]
This looks good to me, @calixteman do you want to take a look?

**Review by calixteman — APPROVED** [review]
LGTM too. r+
Thanks for doing that.

**Review by marco-c — APPROVED** [review]

**Pull request merged**
